### PR TITLE
1.6 update

### PR DESCRIPTION
**Pull request by jamsethoth**
Created new 1.6 version, updating all changed assets and adding new assets

### CODE REVIEW

**Comment by prikhodkop** [comment]
Hi! Why did you close the pull request? I think i can test and merge it into master.

**Comment by prikhodkop** [comment]
Also, you don't need to copy everything from 1.5 to 1.6, only things that changed. All missing assets in 1.6 would be automatically loaded from default version (which is 1.5)

**Comment by jamsethoth** [comment]
Yeah, I deleted it because I realized I could do it better, and then since
my repo got screwed and I decided to be safe and just reclone and apply the
changes again. I'll raise a pr today or tomorrow with the updates.

**Comment by jamsethoth** [comment]
Okay, I have raised a new PR

**Pull request closed without merging**
